name: Run Adobe AIO-CLI Command

on:
  workflow_dispatch:

jobs:
  run-aio-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 16 as Unsecure Version
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      run: echo "Node.js 18 will be used"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Adobe AIO-CLI
      run: npm install -g @adobe/aio-cli

    - name: Install Dependencies
      run: npm install

    - name: Install yq for YAML Parsing
      run: |
        sudo apt-get install -y yq

    - name: Read YAML and Create Action List
      id: generate_action_list
      run: |
        yaml_file="app.config.yaml"
        actions=$(yq eval '.application.runtimeManifest.packages."EDS-Asset-Tracker1".actions | to_entries | map("\(.key): \(.value.function)") | join(", ")' $yaml_file)
        echo "actions=$actions" >> $GITHUB_ENV

    - name: Echo Action List
      run: |
        echo "Action List: ${{ env.actions }}"

    - name: Configure AIO-CLI Runtime Properties
      env:
        AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
        AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        AIO_RUNTIME_APIHOST: ${{ secrets.AIO_RUNTIME_APIHOST || 'https://adobeioruntime.net' }}
      run: |
        echo "AIO_RUNTIME_AUTH: $AIO_RUNTIME_AUTH"
        echo "AIO_RUNTIME_NAMESPACE: $AIO_RUNTIME_NAMESPACE"
        echo "AIO_RUNTIME_APIHOST: $AIO_RUNTIME_APIHOST"
        aio rt property get --all # Replace with your desired AIO-CLI command
