name: Extract First Package Name

on:
  workflow_dispatch:

jobs:
  extract-package-name:
    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 20 as Unsecure Version
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      run: echo "Node.js 20 will be used"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install yq for YAML Parsing
      run: |
        # Download and install yq
        curl -sLo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.23.1/yq_linux_amd64
        chmod +x /usr/local/bin/yq

    - name: Extract First Package Name
      id: extract_package_name
      run: |
        yaml_file="app.config.yaml"
        # Display the version of yq for debugging
        yq --version
        # Extract and debug the YAML parsing command
        first_package_name=$(yq eval '.application.runtimeManifest.packages | keys | .[0]' $yaml_file)
        echo "First Package Name: $first_package_name"
        echo "FIRST_PACKAGE_NAME=$first_package_name" >> $GITHUB_ENV

    - name: Echo First Package Name
      run: |
        echo "First Package Name: ${{ env.FIRST_PACKAGE_NAME }}"
